// <auto-generated />
using System;
using API_Authenticate_220522.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Authenticate_220522.Migrations
{
    [DbContext(typeof(TokenDBContext))]
    [Migration("20220523054330_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("API_Authenticate_220522.Models.Token", b =>
                {
                    b.Property<string>("token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_expired")
                        .HasColumnType("bit");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("token");

                    b.ToTable("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
